=== dineshmetkari/hercules-password-protector/trunk/hercules-password-protector/src/br/com/thecodebakers/hppfree/schema/hppfreebackup.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
/*
 * Copyright (C) 2011 The Code Bakers
 * Authors: Cleuton Sampaio e Francisco Rodrigues
 * e-mail: thecodebakers@gmail.com
 * Project: http://code.google.com/p/hercules-password-protector
 * Site: http://thecodebakers.blogspot.com
 *
 * Licensed under the GNU GPL, Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://gplv3.fsf.org/
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * @author Cleuton Sampaio e Francisco Rogrigues - thecodebakers@gmail.com
 */


 -->
 	<xs:schema 
 		targetNamespace="http://br.com.thecodebakers.hpp/hppfreebackup" 
 		elementFormDefault="qualified" 
 		xmlns:tns="http://br.com.thecodebakers.hpp/hppfreebackup"
 		xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- Cada entrada é composta pelo texto1 - UUID do Local, e pelo texto2 - dados do local encriptados -->
    <xs:complexType name="TEntrada">
    	<xs:sequence>
    		<xs:element name="texto1" type="xs:string"></xs:element>
    		<xs:element name="texto2" type="xs:string"></xs:element>
    	</xs:sequence>
    </xs:complexType>

	<!-- Este é o vetor de entradas do banco -->
    <xs:complexType name="TEntradas">
    	<xs:sequence>
    		<xs:element name="entrada" type="tns:TEntrada"></xs:element>
    	</xs:sequence>
    </xs:complexType>

	<!-- O elemento versaoData representa o DATABASE_VERSION.
		 O elemento hashTexto é o hashcode MD5 da lista de dados, encriptada, em formato plaintext, sem os tags, separada por ponto-e-vírgula.
		 o elemento data é a data e hora em que foi feito este backup.
	 -->
	<xs:complexType name="TBackup">
		<xs:sequence>
	   		<xs:element name="versaoData" type="xs:string"></xs:element>
	   		<xs:element name="hashTexto" type="xs:string"></xs:element>
	   		<xs:element name="data" type="xs:dateTime"></xs:element>
	   		<xs:element name="entradas" type="tns:TEntradas"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:element name="hppfreeBackup" type="tns:TBackup"></xs:element>
    
</xs:schema>

=== dineshmetkari/hercules-password-protector/hercules-password-protector/bin/br/com/thecodebakers/hppfree/schema/hppfreeBackup01_sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:hppfreeBackup xmlns:tns="http://br.com.thecodebakers.hpp/hppfreebackup" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://br.com.thecodebakers.hpp/hppfreebackup hppfreebackup.xsd ">
  <tns:versaoData>1</tns:versaoData>
  <tns:hashTexto>-12023923</tns:hashTexto>
  <tns:data>2001-12-31T12:00:00</tns:data>
  <tns:entradas>
    <tns:entrada>
      <tns:texto1>texto1</tns:texto1>
      <tns:texto2>texto2</tns:texto2>
    </tns:entrada>
  </tns:entradas>
</tns:hppfreeBackup>
